language: node_js
cache:
  directories:
  - node_modules
  - src/bower
before_script:
- bower install
- gem install scss-lint
after_script:
- grunt mocha_istanbul && grunt coveralls
- grunt scsslint --force
notifications:
  email: false
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: dominik.tornow@gmail.com
  password:
    secure: d8HCJ/9Ay3ddc4ZLhg99uwPKfAKxD8NIe8RmoFd7cWKToRLzvlgB+nKoAMgWon/79ZWAtYINTxFEgxGwnMSoXDKPXp/L1o95KHwhnCYJUvJYSb/gmjFcLMf+VBv/HJCYRGxyBY9fBcbGxEsER4V9XDscI+Nt03bX7vabXgfIGyc=
  organization: GithubTeam
  space: development
  on:
    repo: reviewninja/review.ninja
    branch: master
