language: node_js
cache:
  directories:
  - node_modules
  - src/bower
before_script:
- bower install
- gem install scss-lint
after_script:
- grunt mocha_istanbul && grunt coveralls
- grunt scsslint --force
- ./.cf.sh review-ninja-staging