language: node_js
cache:
  directories:
  - node_modules
  - src/bower
before_script:
- bower install
- gem install compass
- grunt sass
notifications:
  email: false
deploy:
  provider:
    provider: cloudfoundry
  api: api.run.pivotal.io
  username: fbranczyk@gmail.com
  password:
    secure: Ije9TY5nIp672Ox5EkkokmMEoQVZgXVKiqUxV69TaZjz24PIrFwiMTpkz5LpPOCIUGbAFK67Y9zVCXHctl+pnrUBryGCSvApiRBzpxX2I613gmX63/7wBx+92S0qEVZ6sF8w5mi6BAsMlIwpeP8RUShm7aiYTsJgf68Ml02FCY4=
  organization: Github Team
  space: development
  on:
    repo: reviewninja/review.ninja
