language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g bower
  - bower install
notifications:
  webhooks: 
    urls:
      - http://webhooks.nodejitsu.com/1/deploy
    on_success: always
    on_failure: never